project:
  type: website

website:
  title: "Good Enough Computing in Science 👍⚖️🧑‍💻🧪"
  # navbar: true
    # left:
      # - href: index.qmd
        # text: Home
      # - about.qmd
  page-footer: by Igors Dubanevics | 2025 | MIT License

  sidebar:
    style: "floating"
    # search: true
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "0. Setting Up"
        href: 00-setting-up.qmd
      - text: "1. Terminal"
        href: 01-terminal.qmd
      - text: "2. Project Structure"
        href: 02-project-structure.qmd
      - text: "3. Version Control"
        href: 03-version-control.qmd
      - text: "4. Virtual Environment"
        href: 04-virtual-environment.qmd
      - text: "5. Automation"
        href: 05-automation.qmd
      - text: "VS Code"
        href: 00-vs-code.qmd
      # - text: "About"
      #   href: about.qmd
      # -  auto: 0?_*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    callout-appearance: simple

